### ISSUE TITLE
Update to permitio/opal-client

### ISSUE THREAD

**Issue by Hongbo-Miao** [permitio/opal-fetcher-postgres#11]
It would be great to update `authorizon/opal-client` to `permitio/opal-client`! 😃
https://github.com/permitio/opal-fetcher-postgres/blob/master/Dockerfile#L1

Also note once switch to `permitio/opal-client`, you will see

> SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.

**Comment by orweis** [comment]
@Hongbo-Miao ! so good to hear from you :)
This is a good catch - I've made the change - thank you.
