### ISSUE TITLE
Cedar can only change the entire data structure at once.

### ISSUE THREAD

**Issue by kai-draft** [permitio/opal-fetcher-postgres#20]
Hello.

I'd like to set up a postgres fetch provider.
What does the error below mean?

Here is the opal-server-configmap and the captured image.

![image](https://github.com/user-attachments/assets/2051dc0f-8d74-4989-954c-9d3275666638)

![image](https://github.com/user-attachments/assets/4a4a05b1-08d5-4988-93c9-9ae14be0f0bd)

Thank you.

**Comment by orweis** [comment]
Hi @HonorBn :)
Cedar (unlike OPA) cannot (At this point in time) update a single subest of its data, but has to have the entire data object pushed at once. You need to configure your data fetcher to edit all of the data.

CC: @omer9564
